import { HttpException, HttpStatus } from '@nestjs/common'

export const ErrorCodes = {
  PROJECT_NOT_FOUND: 'AI_VIDEO_PROJECT_NOT_FOUND',
  PROJECT_NAME_CONFLICT: 'AI_VIDEO_PROJECT_NAME_CONFLICT',
  PROJECT_CREATE_FAILED: 'AI_VIDEO_PROJECT_CREATE_FAILED',
  PROJECT_UPDATE_FAILED: 'AI_VIDEO_PROJECT_UPDATE_FAILED',
  PROJECT_DELETE_FAILED: 'AI_VIDEO_PROJECT_DELETE_FAILED',
  SCENE_NOT_FOUND: 'AI_VIDEO_SCENE_NOT_FOUND',
  SCENE_CREATE_FAILED: 'AI_VIDEO_SCENE_CREATE_FAILED',
  SCENE_UPDATE_FAILED: 'AI_VIDEO_SCENE_UPDATE_FAILED',
  SCENE_DELETE_FAILED: 'AI_VIDEO_SCENE_DELETE_FAILED',
  CHARACTER_NOT_FOUND: 'AI_VIDEO_CHARACTER_NOT_FOUND',
  CHARACTER_CREATE_FAILED: 'AI_VIDEO_CHARACTER_CREATE_FAILED',
  ASSET_NOT_FOUND: 'AI_VIDEO_ASSET_NOT_FOUND',
  ASSET_UPLOAD_FAILED: 'AI_VIDEO_ASSET_UPLOAD_FAILED',
  ASSET_DELETE_FAILED: 'AI_VIDEO_ASSET_DELETE_FAILED',
  PROVIDER_NOT_FOUND: 'AI_VIDEO_PROVIDER_NOT_FOUND',
  PROVIDER_INACTIVE: 'AI_VIDEO_PROVIDER_INACTIVE',
  PROVIDER_UNAVAILABLE: 'AI_VIDEO_PROVIDER_UNAVAILABLE',
  RENDER_SUBMIT_FAILED: 'AI_VIDEO_RENDER_SUBMIT_FAILED',
  RENDER_NO_SCENES: 'AI_VIDEO_RENDER_NO_SCENES',
  RENDER_CANCEL_FAILED: 'AI_VIDEO_RENDER_CANCEL_FAILED',
  JOB_NOT_FOUND: 'AI_VIDEO_JOB_NOT_FOUND',
  JOB_CANCEL_FAILED: 'AI_VIDEO_JOB_CANCEL_FAILED',
  BRAND_KIT_NOT_FOUND: 'AI_VIDEO_BRAND_KIT_NOT_FOUND',
  VALIDATION_ERROR: 'AI_VIDEO_VALIDATION_ERROR',
  INTERNAL_ERROR: 'AI_VIDEO_INTERNAL_ERROR',
  USER_NOT_FOUND: 'AI_VIDEO_USER_NOT_FOUND',
  PRISMA_UNIQUE_CONSTRAINT: 'AI_VIDEO_UNIQUE_CONSTRAINT',
  PRISMA_FOREIGN_KEY: 'AI_VIDEO_FOREIGN_KEY_VIOLATION',
  PRISMA_NOT_FOUND: 'AI_VIDEO_RECORD_NOT_FOUND',
}

const ErrorCodeStatus: Record<string, number> = {
  [ErrorCodes.USER_NOT_FOUND]: 404,
  [ErrorCodes.PROJECT_NOT_FOUND]: 404,
  [ErrorCodes.PROJECT_NAME_CONFLICT]: 409,
  [ErrorCodes.PROJECT_CREATE_FAILED]: 500,
  [ErrorCodes.PROJECT_UPDATE_FAILED]: 500,
  [ErrorCodes.PROJECT_DELETE_FAILED]: 500,
  [ErrorCodes.SCENE_NOT_FOUND]: 404,
  [ErrorCodes.SCENE_CREATE_FAILED]: 500,
  [ErrorCodes.SCENE_UPDATE_FAILED]: 500,
  [ErrorCodes.SCENE_DELETE_FAILED]: 500,
  [ErrorCodes.CHARACTER_NOT_FOUND]: 404,
  [ErrorCodes.CHARACTER_CREATE_FAILED]: 500,
  [ErrorCodes.ASSET_NOT_FOUND]: 404,
  [ErrorCodes.ASSET_UPLOAD_FAILED]: 500,
  [ErrorCodes.ASSET_DELETE_FAILED]: 500,
  [ErrorCodes.PROVIDER_NOT_FOUND]: 404,
  [ErrorCodes.PROVIDER_INACTIVE]: 400,
  [ErrorCodes.PROVIDER_UNAVAILABLE]: 503,
  [ErrorCodes.RENDER_SUBMIT_FAILED]: 500,
  [ErrorCodes.RENDER_NO_SCENES]: 400,
  [ErrorCodes.RENDER_CANCEL_FAILED]: 500,
  [ErrorCodes.JOB_NOT_FOUND]: 404,
  [ErrorCodes.JOB_CANCEL_FAILED]: 500,
  [ErrorCodes.BRAND_KIT_NOT_FOUND]: 404,
  [ErrorCodes.VALIDATION_ERROR]: 400,
  [ErrorCodes.INTERNAL_ERROR]: 500,
  [ErrorCodes.PRISMA_UNIQUE_CONSTRAINT]: 409,
  [ErrorCodes.PRISMA_FOREIGN_KEY]: 400,
  [ErrorCodes.PRISMA_NOT_FOUND]: 404,
}

export class BusinessError extends HttpException {
  public readonly errorCode: string

  constructor(errorCode: string, message?: string, status?: number) {
    const httpStatus = status ?? ErrorCodeStatus[errorCode] ?? 500
    const defaultMessage = message || errorCode
    super({ errorCode, message: defaultMessage }, httpStatus)
    this.errorCode = errorCode
  }
}
